# Generated by Django 4.0.4 on 2022-06-11 11:03

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlabels',
            name='label',
        ),
        migrations.RemoveField(
            model_name='productlabels',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='labels',
        ),
        migrations.AddField(
            model_name='flag',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='flag',
            field=models.ForeignKey(default=products.models.Flag.get_defalut_flag, on_delete=django.db.models.deletion.CASCADE, to='products.flag'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='ProductLabels',
        ),
    ]
