# Generated by Django 4.0.4 on 2022-06-06 11:34

import core.storages
from django.db import migrations, models
import products.utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=core.storages.select_storage, upload_to=products.utils.genrate_image_name),
        ),
    ]
