# Generated by Django 4.0.4 on 2022-06-11 11:04

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productlabels_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='flag',
            field=models.ForeignKey(default=products.models.Flag.get_defalut_flag, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.flag'),
        ),
    ]
